### ISSUE TITLE
Cannot find module json2json

### ISSUE THREAD

**Issue by shachindrasingh** [joelvh/json2json#11]
Hi,
I want to use this json2json for message transformation, I had install this model using npm.
but still i am getting the error "Cannot find module json2json".
One more thing that i had create this application using strongloop framework.
thanks.

**Comment by chazzlabs** [comment]
This issue was written some time ago, but I ran into this while trying to require json2json in a node project.  I figured I'd document how to load the module for anyone who might also run into this.

Install coffee-script with ```npm install coffee-script```.  In the file in which you want to use json2json, first add ```require('coffee-script').register();```.  You can now add ```require('json2json2')``` to have the module load properly.

**Comment by joelvh** [comment]
@chazzlabs thanks for the info. Did the latest merge from PR #16 address this? If not, can you submit a PR with your notes added to the README? Thanks!

**Comment by chazzlabs** [comment]
@joelvh Looks good! I was able to install json2json in a fresh project successfully with no other dependencies. Thank!

**Comment by joelvh** [comment]
Great, thanks @chazzlabs
